import Testing
@testable import ModelHike

@Suite struct PrintableParser_Tests {
    private func parseModel(_ dsl: String) async throws -> (LoadContext, ModelSpace) {
        let ctx = LoadContext(config: PipelineConfig())
        let modelSpace = try await ModelFileParser(with: ctx).parse(string: dsl, identifier: "PrintableParser_Tests")
        await ctx.model.append(contentsOf: modelSpace)
        try await ctx.model.resolveAndLinkItems(with: ctx)
        return (ctx, modelSpace)
    }

    private func moduleNamed(_ name: String, space: ModelSpace) async -> C4Component? {
        for module in await space.modules.snapshot() {
            if await module.name == name { return module }
        }
        return nil
    }

    @Test func printableParsesDirectivesHeaderFooterSectionsTablesAndPageBreaks() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Invoice Printable (Order, Customer)
            /#####/
            @ output:: pdf, html
            @ page:: A4, portrait
            @ locale:: en-US
            header:
            | Invoice {{ order.id }}
            section Lines (table):
            | Line item summary
            table: order.lines
            column: SKU -> sku
            column: Qty -> quantity
            pageBreak: after section
            footer:
            | Thank you
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)

        #expect(await printable.name == "InvoicePrintable")
        #expect(await printable.boundObjects == ["Order", "Customer"])
        #expect(await printable.outputFormats == ["pdf", "html"])
        #expect(await printable.page == "A4, portrait")
        #expect(await printable.locale == "en-US")
        #expect(await printable.headerRows.first?.text == "Invoice {{ order.id }}")
        #expect(await printable.footerRows.first?.text == "Thank you")
        #expect(await printable.pageBreaks.first?.rule == "after section")

        let section = try #require(await printable.sections.first)
        #expect(section.name == "Lines")
        #expect(section.layout == "table")
        #expect(section.rows.first?.text == "Line item summary")
        let table = try #require(section.tables.first)
        #expect(table.source == "order.lines")
        var columnTitles: [String] = []
        var columnBindings: [String] = []
        for column in table.columns {
            columnTitles.append(column.title)
            columnBindings.append(column.binding)
        }
        #expect(columnTitles == ["SKU", "Qty"])
        #expect(columnBindings == ["sku", "quantity"])
    }

    @Test func printableParsesConditionalAndStopsBeforeConfig() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Reminder Email (Invoice)
            /#####/
            @ output:: email
            section Body:
            |> IF invoice.overdue
            | Overdue invoice
            end

            Mail Settings (email)
            ::::::::
            from = billing@example.com
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)
        let config = try #require(await module.configObjects.first)

        #expect(await printable.sections.first?.name == "Body")
        #expect(await printable.conditionals.first?.condition == "invoice.overdue")
        #expect(await printable.sections.first?.rows.first?.text == "Overdue invoice")
        #expect(await config.name == "MailSettings")
    }

    @Test func printableWithMultipleSectionsAndNoBoundObjects() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Report
            /#####/
            @ output:: pdf
            section Summary:
            | Total revenue
            section Details (list):
            | Line by line breakdown
            | Per-customer details
            footer:
            | Generated by ModelHike
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)

        #expect(await printable.boundObjects.isEmpty)
        #expect(await printable.sections.count == 2)
        #expect(await printable.sections[0].name == "Summary")
        #expect(await printable.sections[0].layout == nil)
        #expect(await printable.sections[1].name == "Details")
        #expect(await printable.sections[1].layout == "list")
        #expect(await printable.sections[1].rows.count == 2)
        #expect(await printable.footerRows.first?.text == "Generated by ModelHike")
    }

    @Test func printableWithMultipleTablesInOneSection() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Statement (Account)
            /#####/
            @ output:: pdf
            section Lines (table):
            table: account.credits
            column: Date -> date
            column: Amount -> amount
            table: account.debits
            column: Date -> date
            column: Amount -> amount
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)
        let section = try #require(await printable.sections.first)

        #expect(section.tables.count == 2)
        #expect(section.tables[0].source == "account.credits")
        #expect(section.tables[0].columns.count == 2)
        #expect(section.tables[1].source == "account.debits")
        #expect(section.tables[1].columns.count == 2)
    }

    @Test func printableWithoutOutputDirectiveStillParses() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Draft Printable
            /#####/
            section Body:
            | Draft only
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)

        #expect(await printable.outputFormats.isEmpty)
        #expect(await printable.sections.first?.rows.first?.text == "Draft only")
    }

    @Test func printableParsesPageAndLocaleDirectives() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Receipt (Transaction)
            /#####/
            @ output:: thermal
            @ page:: 80mm
            @ locale:: en_GB
            header:
            | Store Name
            section Items:
            | Line items here
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)

        #expect(await printable.boundObjects == ["Transaction"])
        #expect(await printable.page == "80mm")
        #expect(await printable.locale == "en_GB")
        #expect(await printable.outputFormats == ["thermal"])
        #expect(await printable.headerRows.count == 1)
        #expect(await printable.sections.count == 1)
    }

    @Test func printableStopsBeforeNextPrintableBlock() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Invoice (Order)
            /#####/
            @ output:: pdf
            section Body:
            | invoice lines

            Packing Slip (Order)
            /#####/
            @ output:: pdf
            section Body:
            | packing items
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let all = await module.printableObjects
        #expect(all.count == 2)

        let invoice = try #require(all.first)
        #expect(await invoice.name == "Invoice")

        let slip = try #require(all.last)
        #expect(await slip.name == "PackingSlip")
    }

    @Test func printableWithPageBreakAndConditional() async throws {
        let (_, space) = try await parseModel("""
            ===
            Svc
            ===
            + Billing

            === Billing ===

            Report (Account)
            /#####/
            @ output:: pdf
            section Summary:
            | Account overview
            pageBreak: before-details
            |> IF account.active
            | Active badge
            section Details:
            | Detailed lines
            """)

        let module = try #require(await moduleNamed("Billing", space: space))
        let printable = try #require(await module.printableObjects.first)

        #expect(await printable.pageBreaks.count == 1)
        #expect(await printable.pageBreaks.first?.rule == "before-details")
        #expect(await printable.conditionals.count == 1)
        #expect(await printable.conditionals.first?.condition == "account.active")
        #expect(await printable.sections.count == 2)
    }
}
