//
//  InputFolder.swift
//  ModelHike
//  https://www.github.com/modelhike/modelhike
//

import Foundation

public class InputFolder {
    public var name: String?
    public var subFolders:[InputFolder]?
    public private(set) var items:[InputFile] = []
    
    public var autoGeneratedFileNumber: Int = 1
    
    public func add(_ doc: Document) {
        let filename = "file\(autoGeneratedFileNumber)"
        autoGeneratedFileNumber += 1
        add(doc, filename: filename)
    }
    
    public func add(_ doc: Document, filename: String) {
        items.append(InputFile(doc, filename: filename))
    }
    
    public func add(_ doc: Document, to fileSetName: String) {
        if let folder = subFolder(of: fileSetName) {
            folder.add(doc)
        }
    }
    
    public func add(_ doc: Document,  filename: String, to fileSetName: String) {
        if let folder = subFolder(of: fileSetName) {
            folder.add(doc, filename: filename)
        }
    }
    
    public lazy var content: InputFolder? = { subFolder(of: "content") }()
    public lazy var pages: InputFolder? = { subFolder(of: "pages") }()
    public lazy var templates: InputFolder? = { subFolder(of: "templates") }()
    public lazy var assets: InputFolder? = { subFolder(of: "assets") }()
    
    public func subFolder(of itemName: String) -> InputFolder? {
        guard let folders = self.subFolders else { return nil }
        
        for folder in folders {
            if folder.name == itemName {
                return folder
            }
        }
        
        return nil
    }
}
