//
// OutputFolder.swift
// DiagSoup
// https://www.github.com/diagsoup/diagsoup
//

import Foundation

public protocol PersistableFolder {
    var foldername: String {get}
    var outputFolder: LocalFolder {get}
    func persist() throws
}

public class OutputFolder {
    private var folder: LocalFolder
    public var subFolders:[OutputFolder] = []
    public private(set) var items:[OutputFile] = []
    public private(set) var folderItems:[PersistableFolder] = []
    public var autoGeneratedFileNumber: Int = 1
    
    public var foldername: String { folder.name }
    public var path: LocalPath { folder.path }
    
    public func add(_ file: OutputFile) {
        file.outputPath = self.folder.path
        items.append(file)
    }
    
    public func add(_ folder: PersistableFolder ) {
        self.folderItems.append(folder)
    }
    
    public func add(_ folder: OutputFolder ) {
        self.subFolders.append(folder)
    }
    
    public func add(_ doc: Document) {
        let filename = "file\(autoGeneratedFileNumber)"
        autoGeneratedFileNumber += 1
        add(doc, filename: filename)
    }
    
    public func add(_ doc: Document, filename: String) {
        items.append(OutputDocumentFile(doc, filename: filename))
    }
    
    public func add(_ doc: Document, to fileSetName: String) {
        let folder = subFolder(fileSetName)
        folder.add(doc)
    }
    
    public func add(_ doc: Document,  filename: String, to fileSetName: String) {
        let folder = subFolder(fileSetName)
        folder.add(doc, filename: filename)
    }
    
    public func persist(with context: GenerationContext) throws {
        try self.ensureExists()
        
        for folder in subFolders {
            try folder.persist(with: context)
            context.addGenerated(folderPath: folder.path)
        }
        
        for folder in folderItems {
            try folder.persist()
            context.addGenerated(folderPath: folder.outputFolder)
        }
        
        for item in items {
            try item.persist()
            context.addGenerated(filePath: item.outputPath.string + item.filename)
        }
    }
    
    @discardableResult
    public func ensureExists() throws -> Self {
        try self.folder.ensureExists()
        return self
    }
    
    public func clearFiles() throws {
        try folder.deleteAllFilesAndFolders()
    }
    
    public lazy var content: OutputFolder = { subFolder("content") }()
    public lazy var pages: OutputFolder = { subFolder("pages") }()
    public lazy var templates: OutputFolder = { subFolder("templates") }()
    public lazy var assets: OutputFolder = { subFolder("assets") }()
    
    public func subFolder(_ itemName: String) -> OutputFolder {
        for folder in self.subFolders {
            if folder.folder.name == itemName {
                return folder
            }
        }
        
        return createNewSubFolder(name: itemName)
    }
    
    private func createNewSubFolder(name: String) -> OutputFolder {
        let newSubFolder = OutputFolder(folder.subfolder(at: name))
        self.subFolders.append(newSubFolder)
        return newSubFolder
    }
    
    public init(_ name: String) {
        self.folder = LocalFolder(path: name)
    }
    
    public init(_ path: LocalPath) {
        self.folder = LocalFolder(path: path)
    }
    
    public init(_ folder: LocalFolder) {
        self.folder = folder
    }
}
