//
//  OutputFolder.swift
//  ModelHike
//  https://www.github.com/modelhike/modelhike
//

import Foundation

public protocol PersistableFolder : Actor, SendableDebugStringConvertible, Sendable {
    var foldername: String { get }
    var newFoldername: String { get }
    var outputFolder: OutputFolder? { get }
    func outputFolder(baseFolder: LocalFolder)
    func persist() async throws
}

public actor OutputFolder : SendableDebugStringConvertible {
    internal private(set) var folder: LocalFolder
    public var subFolders: [OutputFolder] = []
    public private(set) var items: [OutputFile] = []
    public private(set) var folderItems: [PersistableFolder] = []
    public var autoGeneratedFileNumber: Int = 1

    public var foldername: String { folder.name }
    public var folderUrl: URL { folder.url }
    public var path: LocalPath { folder.path }

    public func add(_ file: OutputFile) async {
//        if await file.filename.hasSuffix(".env.stage") {
//            await print(file.filename)
//        }
        await file.outputPath( self.folder.path )
        items.append(file)
    }

//    public func add(_ doc: RenderableDocument, to fileSetName: String, renderConfig: RenderConfig) async -> OutputDocumentFile {
//        let folder = await subFolder(fileSetName)
//        return await folder.add(doc, renderConfig: renderConfig)
//    }
//
//    public func add(_ doc: RenderableDocument, filename: String, to fileSetName: String, renderConfig: RenderConfig, type: OutputDocumentFile.InputFileType = .generic) async -> OutputDocumentFile {
//        
//        let folder = await subFolder(fileSetName)
//        return await folder.add(doc, filename: filename, renderConfig: renderConfig, type: type)
//    }
//
//    public func add(_ doc: RenderableDocument, renderConfig: RenderConfig) async -> OutputDocumentFile {
//        let filename = "file\(autoGeneratedFileNumber)"
//        autoGeneratedFileNumber += 1
//        return await add(doc, filename: filename, renderConfig: renderConfig)
//    }
//
//    public func add(_ doc: RenderableDocument, filename: String, renderConfig: RenderConfig, type: OutputDocumentFile.InputFileType = .generic) async -> OutputDocumentFile {
//        let docFile = OutputDocumentFile(doc, filename: filename, renderConfig: renderConfig, type: type)
//        await add( docFile)
//        return docFile
//    }

    public func add(_ subFolder: PersistableFolder) async {
        await subFolder.outputFolder(baseFolder: self.folder)
        self.folderItems.append(subFolder)
    }

    public func add(_ subFolder: OutputFolder) {
        self.subFolders.append(subFolder)
    }
    
    public func persist(with context: GenerationContext) async throws {
        guard items.count > 0 || folderItems.count > 0 || subFolders.count > 0 else {
            return
        }
        
        //create the folder only if any file or sub folder is persisted
        try self.ensureExists()

        if subFolders.isNotEmpty {
            var subRoots: [LocalFolder] = []
            subRoots.reserveCapacity(subFolders.count)
            try await withThrowingTaskGroup(of: LocalFolder?.self) { group in
                for folder in subFolders {
                    group.addTask {
                        try await folder.persist(with: context)
                        return LocalFolder(path: await folder.path)
                    }
                }
                for try await root in group {
                    if let root {
                        subRoots.append(root)
                    }
                }
            }
            await context.addGenerated(folderRoots: subRoots, addFileCount: false)
        }

        if folderItems.isNotEmpty {
            var renderedRoots: [LocalFolder] = []
            renderedRoots.reserveCapacity(folderItems.count)
            try await withThrowingTaskGroup(of: LocalFolder?.self) { group in
                for folder in folderItems {
                    group.addTask {
                        guard let outputFolder = await folder.outputFolder else { return nil }
                        try await folder.persist()
                        return await outputFolder.folder
                    }
                }
                for try await root in group {
                    if let root {
                        renderedRoots.append(root)
                    }
                }
            }
            await context.addGenerated(folderRoots: renderedRoots, addFileCount: true)
        }

        if items.isNotEmpty {
            var filePaths: [String] = []
            filePaths.reserveCapacity(items.count)
            try await withThrowingTaskGroup(of: String?.self) { group in
                for item in items {
                    group.addTask {
                        guard let outputPath = await item.outputPath else { return nil }
                        let name = await item.filename
                        try await item.persist()
                        return (outputPath / name).string
                    }
                }
                for try await path in group {
                    if let path {
                        filePaths.append(path)
                    }
                }
            }
            await context.addGenerated(filePaths: filePaths)
        }
    }

    @discardableResult
    public func ensureExists() throws -> Self {
        try self.folder.ensureExists()
        return self
    }

    public func clearFiles() throws {
        try folder.deleteAllFilesAndFolders()
    }

    public var content: OutputFolder { get async { await subFolder("content") }}
    public var pages: OutputFolder { get async { await subFolder("pages") }}
    public var templates: OutputFolder { get async { await subFolder("templates") }}
    public var assets: OutputFolder { get async { await subFolder("assets") }}

    public func relativeFolder(_ itemName: String) async -> OutputFolder {
        //if existing return that sub folder
        for folder in self.subFolders {
            let lastPath = await String(folder.folderUrl.relativePath.suffix(itemName.count))
            if lastPath.is(itemName) {
                return folder
            }
        }

        //else, create a new sub folder, with the relative path
        return createNewRelativeSubFolder(relativePath: itemName)
    }
    
    private func createNewRelativeSubFolder(relativePath: String) -> OutputFolder {
        let folder = LocalFolder(relativePath: relativePath, basePath: self.folder)
        let newSubFolder = OutputFolder(folder)
        self.subFolders.append(newSubFolder)
        return newSubFolder
    }
    
    public func subFolder(_ itemName: String) async -> OutputFolder {
        //if existing return that sub folder
        for folder in self.subFolders {
            if await folder.foldername.is(itemName) {
                return folder
            }
        }

        //else, create a new sub folder
        return createNewSubFolder(name: itemName)
    }

    private func createNewSubFolder(name: String) -> OutputFolder {
        let newSubFolder = OutputFolder(folder.subfolder(at: name))
        self.subFolders.append(newSubFolder)
        return newSubFolder
    }

    /// Collects text contents for output files in this folder (recursively), without persisting to disk.
    ///
    /// Includes ``TemplateRenderedFile``, in-memory ``StaticFile`` (string or UTF-8 data), repo-backed ``StaticFile`` (after a best-effort ``StaticFile/render()``),
    /// ``FileToCopy`` (reads source file as UTF-8, or base64 if not valid UTF-8), and ``PlaceHolderFile`` (after ``PlaceHolderFile/render()`` if needed).
    /// Keys are relative paths using `/` (e.g. `Subdir/file.txt`).
    /// Includes subtrees under ``PersistableFolder`` entries (``RenderedFolder``, ``StaticFolder``).
    public func snapshot(prefix: String = "") async -> [String: String] {
        var result: [String: String] = [:]
        for item in items {
            guard let pair = await Self.snapshotStringPair(for: item) else { continue }
            let key: String
            if prefix.isEmpty {
                key = pair.name
            } else {
                key = "\(prefix)/\(pair.name)"
            }
            result[key] = pair.text
        }
        for folderItem in folderItems {
            let nestedOut: OutputFolder?
            let newName: String
            if let rendered = folderItem as? RenderedFolder {
                nestedOut = await rendered.outputFolder
                newName = rendered.newFoldername
            } else if let staticFolder = folderItem as? StaticFolder {
                nestedOut = await staticFolder.outputFolder
                newName = staticFolder.newFoldername
            } else {
                continue
            }
            guard let nestedOut else { continue }
            let nextPrefix: String
            if newName == "/" || newName.isEmpty {
                nextPrefix = prefix
            } else if prefix.isEmpty {
                nextPrefix = newName
            } else {
                nextPrefix = "\(prefix)/\(newName)"
            }
            let nested = await nestedOut.snapshot(prefix: nextPrefix)
            for (k, v) in nested {
                result[k] = v
            }
        }
        for sub in subFolders {
            let subName = await sub.foldername
            let nextPrefix = prefix.isEmpty ? subName : "\(prefix)/\(subName)"
            let nested = await sub.snapshot(prefix: nextPrefix)
            for (k, v) in nested {
                result[k] = v
            }
        }
        return result
    }

    /// Best-effort string payload for snapshot dictionaries (UTF-8 text, or base64 for opaque/binary when needed).
    private static func snapshotStringPair(for item: OutputFile) async -> (name: String, text: String)? {
        if let rendered = item as? TemplateRenderedFile {
            guard let contents = await rendered.contents else { return nil }
            let name = rendered.filename
            return (name, contents)
        }
        if let staticFile = item as? StaticFile {
            var text = await staticFile.contents
            if text == nil, let data = await staticFile.data {
                text = String(data: data, encoding: .utf8)
                if text == nil {
                    text = data.base64EncodedString()
                }
            }
            if text == nil {
                try? await staticFile.render()
                text = await staticFile.contents
            }
            if text == nil, let data = await staticFile.data {
                text = String(data: data, encoding: .utf8) ?? data.base64EncodedString()
            }
            guard let text else { return nil }
            let name = staticFile.filename
            return (name, text)
        }
        if let copy = item as? FileToCopy {
            let out = copy.outFile
            let name = await copy.filename
            let text: String
            if let s = try? out.readTextContents() {
                text = s
            } else if let data = try? Data(contentsOf: out.url) {
                text = String(data: data, encoding: .utf8) ?? data.base64EncodedString()
            } else {
                return nil
            }
            return (name, text)
        }
        if let ph = item as? PlaceHolderFile {
            var text = await ph.contents
            if text == nil {
                try? await ph.render()
                text = await ph.contents
            }
            guard let text else { return nil }
            let name = ph.filename
            return (name, text)
        }
        return nil
    }

    public var debugDescription: String { get async {
        return folder.pathString
    }}
    
    public init(_ name: String) {
        self.folder = LocalFolder(path: name)
    }

    public init(_ path: LocalPath) {
        self.folder = LocalFolder(path: path)
    }

    public init(_ folder: LocalFolder) {
        self.folder = folder
    }
}
